### ISSUE TITLE
Create Event for my shift

### ISSUE THREAD

**Issue by KreisLiga** [codycodes/microsoft_power_automate#1]
Hi,

i was very happy, when i found your Flow.

But i keep running in the same error and cant seem to find the solution.
Could you please be kind enough to take a look?

When creating an event in my Calendar, i get a bad request (400) for the timezone, afterwards the flow ends..

Regards

**Comment by codycodes** [comment]
Hey KreisLiga!

Thanks for opening an issue. Here's what I did to get a working TZ:
You can place your TimeZone in the `USER INPUT: Time Zone` variable like the following:
![image](https://user-images.githubusercontent.com/8005593/73220739-022ee300-4114-11ea-8691-c721035785f4.png)

To get your TimeZone, you can look it up in the _Convert to Time Zone_ action and select yours from the list. You then need to copy this TZ into the variable above:
![image](https://user-images.githubusercontent.com/8005593/73220956-82eddf00-4114-11ea-91a6-14d451d1774b.png)
You'll end up with a String like: **(UTC-03:00) Cayenne, Fortaleza**, which you can copy into the variable above. I designed the flow like this to make it easier to input as there are multiple steps to getting it working, unfortunately.

Try this, and if it isn't working It may also be useful if you can tell me if you're using the Google Calendar one or the Outlook flow.

One other thing you can try is to choose the timezone directly by going into the individual actions that reference it and choosing it from the dropdown.

**Comment by KreisLiga** [comment]
Thank You! It worked for me.
