### ISSUE TITLE
No Payload delivered when using date filters on GetShifts

### ISSUE THREAD

**Issue by ryanmccoy123** [codycodes/microsoft_power_automate#3]
Hi, Great use of flow on this project! Was really great to find an example of what I am trying to put together.. I am hitting an issue though, when I apply the date filters in my Shifts flow it does not deliver any payload. But when dates are removed it delivers the 100 row max.. is there anything different you would suggest I try?

<img width="234" alt="Payload - Success" src="https://user-images.githubusercontent.com/64833307/81147220-c22c9700-8f71-11ea-92a4-cad1a2ceb7cd.PNG">

<img width="324" alt="Payload Fial" src="https://user-images.githubusercontent.com/64833307/81147203-ba6cf280-8f71-11ea-9f3a-1aa11dfae179.PNG">

**Comment by codycodes** [comment]
The main things I would check would start with ensuring the Shifts exist. 

One thing I’m not sure of is if you’re grabbing Shifts for everyone or just yourself. There’s a Boolean true/false for this:

![image](https://user-images.githubusercontent.com/8005593/81189618-a32b0680-8f6b-11ea-9552-ec284a3cb6b4.jpeg)

You can also check different dates to see if there’s some other issue but of course you’ve shared that it’s partially working.

Other than that if the Shifts do exist but you’re not seeing them then this could be a bug with the Teams connector itself. This should be reported to Microsoft in that case. Teams is still a preview action for Power Automate.

**Comment by codycodes** [comment]
I'm going to go ahead and close this issue for now, but if you have any more information to add feel free to post.
