### ISSUE TITLE
Uses depreciated Teams API

### ISSUE THREAD

**Issue by Just-Insane** [codycodes/microsoft_power_automate#4]
Hello,

Is there any plan to update this Power Automate function to use the new Shifts actions in Power Automate rather than the depreciated Teams Shifts actions?

Also, it seems like the new Shifts actions don't let you pull the shifts for everyone in the team unless you are somehow flagged as a manager?

Thanks

**Comment by codycodes** [comment]
Hey there,

Apologies if it’s broken! I’m not able to contribute to the project at this time but if anyone has time to contribute I’ll be happy to merge or point to said code from this repo. I will mark this flow with said updates in this issue on this repo when I’m able.

Unfortunately I no longer work in an environment where we’re using Teams Shifts, so It’s not as easy to test these ideas out. I would need to research more to figure out the new actions or what Shifts even is today :)

I guess it makes sense for the API to not be able to grab other’s shifts with some sort of manager permission. For myself the main utility was to get my shift schedule copied to my Google calendar. Getting other’s shifts was a plus.

Regards,

Cody
